version: "3.1"
name: "find-a-friend-app"
services:
  db:
    container_name: "find-a-friend-postgres-db"
    image: bitnami/postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DATABASE=${POSTGRES_DB}
      - POSTGRES_USERNAME=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
